### ISSUE TITLE
node编译出错

### ISSUE THREAD

**Issue by luoxingran** [dna2github/dna2oslab#20] opened 2022-01-01 14:15 UTC
不知道是不是环境配置出了问题
![9JM}YLQVTJNP34CH3XAH5CL](https://user-images.githubusercontent.com/83531505/147851670-610118b0-f483-4177-99f0-8d5692c0a517.png)

**Comment by luoxingran** [comment] 2022-01-01 14:25
/root/dna2oslab-master/android/node-v16.13.0/out/Release/obj.host/v8_base_without_compiler/deps/v8/src/api/api.o: In function `v8::TryHandleWebAssemblyTrapPosix(int, siginfo_t*, void*)':
api.cc:(.text._ZN2v829TryHandleWebAssemblyTrapPosixEiP9siginfo_tPv+0x1): undefined reference to `v8::internal::trap_handler::TryHandleSignal(int, siginfo_t*, void*)'
/root/dna2oslab-master/android/node-v16.13.0/out/Release/obj.host/v8_base_without_compiler/deps/v8/src/trap-handler/handler-outside.o: In function `v8::internal::trap_handler::EnableTrapHandler(bool)':
handler-outside.cc:(.text._ZN2v88internal12trap_handler17EnableTrapHandlerEb+0x35): undefined reference to `v8::internal::trap_handler::RegisterDefaultTrapHandler()'
/root/dna2oslab-master/android/node-v16.13.0/out/Release/obj.host/v8_base_without_compiler/deps/v8/src/execution/arm64/simulator-arm64.o: In function `v8::internal::Simulator::ProbeMemory(unsigned long, unsigned long)':
simulator-arm64.cc:(.text._ZN2v88internal9Simulator11ProbeMemoryEmm+0x19): undefined reference to `ProbeMemory'
collect2: error: ld returned 1 exit status
make[1]: *** [tools/v8_gypfiles/mksnapshot.host.mk:195: /root/dna2oslab-master/android/node-v16.13.0/out/Release/mksnapshot] Error 1
rm 5687c506960da52e97140f76f1626ad10b7496d2.intermediate 1d70c69eba25618c958a143ee571ac4e7333d160.intermediate 2deb1d37ea39c3748015f3a943d90b48541d7fb9.intermediate 0c46072258786634f31dc1ae19b8203af9991924.intermediate 89ec3b8960bfe43efa87b133a19f3e71d7a4bafe.intermediate
make: *** [Makefile:110: node] Error 2
[root@VM-20-7-centos node-v16.13.0]# cd /root/dna2oslab-master/android/
[root@VM-20-7-centos android]#

**Comment by dna2github** [comment] 2022-01-01 15:52
你的build在link阶段之前可能有什么没有正确编译.
或者也可能是nodejs v16那边有什么新的改动导致fail了；我这边也会再在centos和macos上编译一遍

请提供如下信息，linux系统版本和cpu arch，交叉编译后cpu arch，android api版本，host gcc版本:

```
`uname -a`
$ENVHOST
$ENVTARGET
$ENVANDROIDVER
$HOST_GCC_DIR
```

**Comment by dna2github** [comment] 2022-01-02 02:57
we will fix this soon. now please refer to this issue: https://github.com/nodejs/node/issues/36287

**Comment by dna2github** [comment] 2022-01-02 13:22
the issue is gone from 16.13.1 (error around `trap_handler `); but there is another issue coming; android use libuv (unix:linux); however, it still uses poll.c but linux-core.c depends on epoll.c now. fixing the problem.

**Comment by dna2github** [comment] 2022-01-03 02:25
the build fixed on the latest commit at https://github.com/dna2github/dna2oslab/commit/df2bf1a287c3875d333cd073906bb1f447007dc0

**Closed as completed by dna2github** 2022-01-03 02:25 UTC
Labels: bug
